trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: OpsGuildAutomationRepo
      type: git
      name: DevOps/opsguild.automation
      ref: refs/heads/main
    - repository: templates
      type: github
      name: AVEVA/AVEVA-Samples
      endpoint: AVEVA

variables:
  - name: analysisProject
    value: PIWebAPI_Angular

parameters:
  - name: DefaultTimeoutInterval
    default: 20000
  - name: pool
    default: DevOps Managed Containers Build
  - name: containerDemands
    type: object
    default: ['Agent.OS -equals Windows_NT']

jobs:
  - job: Tests
    condition: ne(variables['Build.Reason'], 'Schedule')
    pool:
      name: ${{ parameters.pool }}
      demands: ${{ parameters.containerDemands }}
    variables:
      - name: DEFAULT_TIMEOUT_INTERVAL
        value: ${{ parameters.DefaultTimeoutInterval }}
    steps:
      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'PIWebAPI, AFServerName, DataArchiveName, Username, Password'

      - template: '/run-tests.yml'
        parameters:
          projectPath: $(Build.SourcesDirectory)

  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
    parameters:
      buildSteps:
        - template: '/miscellaneous/build_templates/appsettings.yml@templates'
          parameters:
            secrets: 'PIWebAPI, AFServerName, DataArchiveName, Username, Password'

        - script: npm ci
          displayName: 'Install dependencies'

        - script: npm run build
          displayName: 'Build'
