trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: analysisProject
    value: PIWebAPI_Angular

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'PIWebAPI, AFServerName, DataArchiveName, Username, Password'

      - template: '/run-tests.yml'
        parameters:
          projectPath: $(Build.SourcesDirectory)

  - job: Analysis
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'PIWebAPI, AFServerName, DataArchiveName, Username, Password'

      - script: npm ci
        displayName: 'Install dependencies'

      - script: npm run build
        displayName: 'Build'

      - template: '/miscellaneous/build_templates/analysis.yml@templates'
